// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search-devops-privacy', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search-devops-privacy', async function() {
    // Test name: search-devops-privacy
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.google.com/")
    // 2 | setWindowSize | 771x695 | 
    await driver.manage().window().setRect(771, 695)
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | click | css=#introAgreeButton .RveJvd | 
    await driver.findElement(By.css("#introAgreeButton .RveJvd")).click()
    // 5 | selectFrame | relative=parent | 
    await driver.switchTo().defaultContent()
    // 6 | type | name=q | devops
    await driver.findElement(By.name("q")).sendKeys("devops")
    // 7 | sendKeys | name=q | ${KEY_ENTER}
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    // 8 | click | css=.hlcw0c:nth-child(4) > .g:nth-child(1) .LC20lb > span | 
    await driver.findElement(By.css(".hlcw0c:nth-child(4) > .g:nth-child(1) .LC20lb > span")).click()
  })
})
